# Generated by Django 3.2.7 on 2021-09-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('population', models.IntegerField(blank=True)),
            ],
        ),
    ]
