# Generated by Django 3.2.7 on 2021-09-28 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buzz', '0002_neighborhood'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
                ('identification_number', models.IntegerField(blank=True)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('neighborhood', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='buzz.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('neighborhood', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='buzz.neighborhood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buzz.user')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buzz.user'),
        ),
    ]
