# Generated by Django 3.2.7 on 2021-09-29 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buzz', '0004_alter_user_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='neighborhood',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buzz.neighborhood'),
        ),
    ]
